### ISSUE TITLE
Script executes on start of Homebridge

### ISSUE THREAD

**Issue by CaptBeard** [PJCzx/homebridge-programmableswitch#1]
Quick question:

I'm trying to use this to execute a simple Philips Hue python script when I tap the switch in HomeKit. Ideally it will be linked to a scene.
What options do I need for that to work?

Right now, the script executes as soon as Homebridge runs.
The switch in HomeKit reports "off".

Great work so far, keep it up!

**Comment by PJCzx** [comment]
Why don’t you use homebridge-philipshue ? It work as a charm

Pierre-Julien Cazaux,
