### ISSUE TITLE
Many thanks...

### ISSUE THREAD

**Issue by Mohamed-EGY** [PJCzx/homebridge-programmableswitch#2]
You have no idea since when i'm trying to do this, finally i can make the TV turn on/of.
Thank you :1st_place_medal: 
Now i'm trying to control TV volume, there's any ideas ??

**Comment by PJCzx** [comment]
Thank you very much. Once I started the implementation of the Speaker type but it wasn’t even managed by iOS Home app yet so I give it up. Maybe thing changed and I advise you to search such a plugin or something. Good luck and if you find anything please provide a feedback :)

**Comment by PJCzx** [comment]
It’s even still commented in the code of ‘’’index.js’’’ as ‘’’this.speakerService’’’ try it a little bit maybe but it’s probably not finished since I wasn’t able te test m’y work.
